---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

#Check working directory
```{r}
getwd()
```
#Importing dataset
```{r}
#import ManyBabies1DataExport(05-01-2018) wide dataset
wide_dataset <- read.delim("../data/ManyBabiesDataExport.csv",sep = ",")
trial_data <- read.delim("../data/MB1_TrialDataUpdated.csv", sep = ",", na.strings = c("NA", ""))
orders <- read.delim("../data/MB1_orders.csv", sep = ",")
participants <- read.delim("../data/MB1_MasterSubjectList.csv", sep = ",")

```

```{r}
#loading  tidyverse packages
library(tidyverse)
```
#Cleaning participant data
```{r}
participants <- participants %>%
  mutate(subid = paste(MB_group_6_vs_12, subid..ManyBabies., sep = "_")) %>%
  mutate(order = trial_order_manybabies) %>%
  select(subid, order)
```

#Manipulating Tobii data
```{r}

#renaming participant column name variable to subid
wide_dataset <- rename(wide_dataset,   subid = X)

#converting from wide to long dataset and renaming variables in long dataset
long_dataset = wide_dataset %>%
 gather(key =trial, value = total_fixation, Total.Fixation.Duration..Include.Zeros._ADS1_ADS1_Sum:Total.Fixation.Duration..Include.Zeros._train2_train2_Sum.3, factor_key=TRUE) %>%
  arrange(subid, trial) %>%
  mutate(trial = gsub("Total.Fixation.Duration..Include.Zeros._", "", trial)) %>%
  mutate(trial = sub("_.*", "", trial)) 

#removing the "all recordings" rows
long_dataset <- subset(long_dataset, subid != "All Recordings")

#creating new variable column for trial type
long_dataset$trial_type <- substr(long_dataset$trial, 1,3)

#moving columns around 
long_dataset <- long_dataset [,c(1, 4, 2, 3)]

#finding the largest value within every trial 
long_dataset_clean <- long_dataset %>%
  dplyr::group_by(subid, trial) %>%
  dplyr::summarize(total_fixation = max(total_fixation, na.rm=T)) 

#creating new variable column for trial type in new dataframe
long_dataset_clean$trial_type <- substr(long_dataset_clean$trial, 1,3)

#seperating _ into its own columns
long_dataset_clean <- separate(long_dataset_clean, subid, into = c("STUDY", "STUDYID", "WORSE"))

#deleting columns "BAD" and "WORSE"
long_dataset_clean[[3]] <- NULL

#merging BABY and BAD column together to create subid column
long_dataset_clean <- transform(long_dataset_clean, subid=paste(STUDY, STUDYID, sep="_"))

#deleting individual columns "BABY" and "BAD"
long_dataset_clean[[1]] <- NULL
long_dataset_clean[[1]] <- NULL

#reordering columns
long_dataset_clean <- long_dataset_clean [,c(4, 3, 1, 2)]

#renaming values of "tra" to "training"
long_dataset_clean$trial_type[long_dataset_clean$trial_type == "tra"] <- "training"

```

#Cleaning trial data
```{r}
trial_data <- trial_data %>%
  mutate(subid = as.factor(subid)) %>%
  mutate(trial_type = as.factor(trial_type)) %>%
  mutate(trial_num = as.numeric(trial_num)) %>%
  select(-stimulus, -looking_time, -MovieStart, -MovieEnd, -TrialTime) 

```

#Merging Tobii with participants and order and cleaning up file
```{r}
long_dataset_clean <- long_dataset_clean %>%
  left_join(participants) %>%
  left_join(orders) %>%
  left_join(trial_data) %>%
  mutate(total_trial_time = as.numeric(total_trial_time)) %>%
  rename(stimulus = trial) %>% 
  rename(looking_time = total_fixation) %>% 
  select(lab, subid, trial_type, stimulus, trial_num, looking_time, total_trial_time, trial_error, trial_error_type, notes) %>%
  mutate(trial_num = trial_num -2) %>% #So first test trial is trial 1
  arrange(subid, trial_num)

long_dataset_clean$trial_num[long_dataset_clean$trial_type == "training"] <- long_dataset_clean$trial_num[long_dataset_clean$trial_type == "training"]  - 1 # Fix training trial numbering

long_dataset_clean$looking_time[is.na(long_dataset_clean$total_trial_time)] <- NA # No looking with no trial time should be NAs


#Replace NA values necessary with NC
replace_na(long_dataset_clean, list(looking_time = "NC"))
replace_na(long_dataset_clean, list(total_trial_time = "NC"))
```


#Exporting R table to .csv file
```{r}
write.csv(long_dataset_clean, "../data/MB1_TrialData.csv", row.names = FALSE)
```

